'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {Plus,Search,Eye,FileText} from 'lucide-react';
import {postJson,requestMessage} from '../lib/client-request';
import type {ContentItem} from '../lib/editorial';

const empty={id:'',title:'',body:'',source:'',published:0};
export default function NewsManager({items}:{items:ContentItem[]}){
 const router=useRouter();
 const [draft,setDraft]=useState(empty),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[preview,setPreview]=useState(false),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 function select(item=empty){if(dirty&&!window.confirm('Há alterações não salvas. Deseja descartá-las?'))return;setDraft(item);setDirty(false);setReviewed(false);setPreview(false);setError('');setMessage('');}
 function change(field:'title'|'body'|'source',value:string){setDraft(d=>({...d,[field]:value}));setDirty(true);setReviewed(false);setMessage('');}
 async function save(published:boolean){setBusy(true);setError('');setMessage('');try{const result=await postJson<{id:string}>('/api/admin/content',{...draft,id:draft.id||undefined,kind:'noticias',published});setDraft(d=>({...d,id:result.id,published:Number(published)}));setDirty(false);setReviewed(false);setMessage(published?'Notícia publicada. Já está disponível no blog.':'Rascunho salvo. Este texto não está visível no blog.');router.refresh();}catch(e){setError(requestMessage(e));}finally{setBusy(false);}}
 const list=items.filter(i=>(filter==='all'||(filter==='published'?!!i.published:!i.published))&&i.title.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 return <div className="news-workspace"><section className="news-library" aria-label="Lista de notícias"><button className="management-primary" onClick={()=>select()} disabled={busy}><Plus size={18}/>Nova notícia</button><label className="management-label">Buscar notícia<span className="news-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pelo título"/></span></label><label className="management-label">Situação<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="draft">Rascunhos</option><option value="published">Publicadas</option></select></label><p className="management-muted">{list.length} notícia(s)</p><ul>{list.map(item=><li key={item.id}><button disabled={busy} aria-current={draft.id===item.id?'true':undefined} onClick={()=>select(item)}><strong>{item.title}</strong><span>{item.published?'Publicada':'Rascunho'} · {new Date(item.updated_at).toLocaleDateString('pt-BR')}</span></button></li>)}</ul>{!list.length&&<p className="management-empty">{items.length?'Nenhuma notícia com esses filtros.':'Comece em “Nova notícia”. Salve um rascunho antes de publicar.'}</p>}</section>
 <section className="news-editor" aria-label="Editor de notícia"><div className="news-editor-heading"><h2>{draft.id?'Editar notícia':'Nova notícia'}</h2><span className="news-status">{dirty?'Alterações não salvas':draft.published?'Publicada':'Rascunho'}</span></div><div className="news-view-controls"><button type="button" aria-pressed={!preview} onClick={()=>setPreview(false)}><FileText size={16}/>Editar</button><button type="button" aria-pressed={preview} onClick={()=>setPreview(true)}><Eye size={16}/>Prévia</button></div>
 <form onSubmit={e=>{e.preventDefault();void save(false);}} aria-busy={busy}><fieldset disabled={busy}>
 {!preview?<><label className="management-label">Título<input required minLength={5} maxLength={160} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="Um título claro para a notícia"/></label><label className="management-label">Texto da notícia<textarea required minLength={20} maxLength={10000} rows={14} value={draft.body} onChange={e=>change('body',e.target.value)} placeholder="Escreva o conteúdo. Separe os parágrafos com uma linha em branco."/></label><small>{draft.body.length.toLocaleString('pt-BR')} / 10.000 caracteres · Texto simples, sem HTML</small><label className="management-label">Fonte ou referência (HTTPS)<input required type="url" value={draft.source} onChange={e=>change('source',e.target.value)} placeholder="https://..."/></label><p className="management-muted">Para conteúdo próprio, informe a página institucional que identifica a origem.</p></>:<article className="news-preview"><p>Prévia do conteúdo</p><h3>{draft.title||'Título da notícia'}</h3><div className="plain-content">{draft.body||'O texto aparecerá aqui enquanto você escreve.'}</div><p>Fonte: {draft.source||'Não informada'}</p></article>}
 <label className="news-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>Conferi o texto, a fonte e autorizo sua publicação no site.</span></label><div className="news-save-actions"><button className="management-secondary" type="submit">{busy?'Salvando…':draft.published?'Retirar do ar e salvar rascunho':'Salvar rascunho'}</button><button className="management-primary" type="button" disabled={!reviewed||busy} onClick={()=>void save(true)}>{draft.published?'Atualizar publicação':'Publicar notícia'}</button></div>
 </fieldset></form><p className="management-success" role="status">{message}</p><p className="form-error" role="alert">{error}</p>{draft.id&&draft.published===1&&<Link href={`/noticias/${draft.id}`} target="_blank">Abrir notícia no blog ↗</Link>}</section></div>;
}
