import Link from 'next/link';
import { publicMetadata } from '../../lib/site';
import { collectionReady, publicConfig } from '../../lib/config';
export const dynamic = 'force-dynamic';
export const metadata = publicMetadata('/ajuda', 'Ajuda e perguntas frequentes', 'Encontre respostas sobre o mapa, o projeto, a participação e os canais públicos do Bahia do Sul.');
import InnerLayout from '../../components/InnerLayout';
export default function HelpPage(){const collecting = collectionReady(); const config = publicConfig(); return <InnerLayout><article className="reading"><h1>Como usar o portal</h1><p className="page-lead">Encontre o que precisa para entender a proposta, explorar o mapa e participar com clareza.</p><p><Link href="/entenda">Primeira visita? Entenda em 2 minutos.</Link></p><nav className="help-topics" aria-label="Assuntos da ajuda"><a href="#proposta">A proposta</a><a href="#mapa">Mapa e dados</a><a href="#participacao">Participação</a></nav><div className="help-list">
<section id="proposta"><h2>Sobre a proposta</h2><details open><summary>Bahia do Sul já é um estado?</summary><p>Não. Este portal apresenta uma proposta em estudo, não uma divisão administrativa aprovada nem um órgão governamental. As seis regiões do mapa são agrupamentos editoriais provisórios.</p><Link href="/projeto">Entenda a natureza do projeto</Link></details><details><summary>Onde encontro autoria e documentos?</summary><p>Consulte as referências associadas a cada informação e o acervo documental. A página de Professor Guilherme diferencia sua identificação pública das informações atribuídas ao documento do projeto.</p><Link href="/historia/professor-guilherme">Conhecer Guilherme e conferir as referências</Link></details></section>
<section id="mapa"><h2>Mapa e dados</h2><details open><summary>Como encontrar meu município?</summary><p>Abra o mapa, digite o nome no campo de busca e selecione o resultado na lista. A busca aceita nomes sem acentos. Se nenhum resultado aparecer, limpe a busca ou use “Ver todas” para remover o filtro regional.</p><p>O endereço guarda região, busca e município selecionado. Você pode copiá-lo e usar os botões Voltar e Avançar do navegador. “Restaurar mapa” limpa os filtros e a seleção.</p><Link href="/territorio">Buscar no mapa</Link></details><details><summary>Por que existem 173 entradas e 171 correspondências?</summary><p>A lista original recebida tem 173 entradas; 171 foram associadas a municípios no cadastro consultado do IBGE. Duas entradas precisam de revisão. Correspondência cadastral não valida a composição territorial proposta.</p><Link href="/fontes">Consultar metodologia e relatório de conferência</Link></details><details><summary>Os destaques mostram todos os municípios?</summary><p>Não. A seleção atual reúne 11 municípios com referências consultadas. A ausência de pesquisa não significa ausência de potencial. População, PIB e área agregados ainda não estão disponíveis.</p></details><details><summary>Posso interpretar as fotos como registros dos locais?</summary><p>Não. As paisagens e imagens temáticas são ilustrações de IA. O retrato do professor tem crédito e fonte próprios. Para informações documentais, consulte as referências textuais.</p></details></section>
<section id="participacao"><h2>Participação e privacidade</h2><details open><summary>{collecting ? 'Como confirmar minha participação?' : 'Por que o formulário está fechado?'}</summary><p>{collecting ? 'Preencha o formulário, confira sua caixa de entrada e confirme sua escolha no link recebido. Somente participações confirmadas entram no total público. Verifique também a pasta de spam.' : 'A coleta depende da confirmação das informações de privacidade e da configuração operacional, incluindo envio de e-mail. Enquanto não for aberta, o formulário é somente para consulta e não recebe dados.'}</p><Link href="/privacidade">Ler o aviso de privacidade e as pendências</Link></details><details><summary>Participar equivale a votar em um plebiscito?</summary><p>Não. Trata-se de manifestação voluntária e simbólica. O certificado também é simbólico, sem valor jurídico ou eleitoral.</p></details><details><summary>Meu link não funciona. O que faço?</summary><p>Use o endereço completo recebido no e-mail. Um link inválido, vencido ou já utilizado não cria um novo apoio. Quando a coleta estiver aberta, solicite outro link no formulário. Se houver falha de conexão, confira a rede e tente novamente; não altere a chave.</p><Link href="/participar">Consultar o formulário</Link></details><details><summary>Como excluir minha participação?</summary><p>Use a chave privada apresentada após a confirmação para acessar o gerenciamento. A exclusão cancela a participação e invalida o certificado. Não compartilhe essa chave.</p><Link href="/participar/gerenciar">Gerenciar participação</Link></details><details><summary>Qual é o canal de atendimento?</summary><p>{config.privacyEmail ? <>Para assuntos sobre seus dados, entre em contato pelo canal de privacidade: <a href={`mailto:${config.privacyEmail}`}>{config.privacyEmail}</a>.</> : 'O canal de privacidade ainda precisa de confirmação. Não publicamos contatos presumidos como autorizados. Você pode conferir o estado da coleta no aviso de privacidade.'}</p><Link href="/privacidade">Conferir o status de privacidade</Link></details></section>
</div></article></InnerLayout>}
