import Link from 'next/link';
import InnerLayout from '../../components/InnerLayout';
import ParticipationForm from '../../components/ParticipationForm';
import {collectionReady,publicConfig} from '../../lib/config';
import dataset from '../../data/territory.json';
import { publicMetadata } from '../../lib/site';
export const metadata = publicMetadata('/participar', 'Participar do Bahia do Sul', 'Conheça formas de acompanhar o projeto Bahia do Sul, participar de atividades públicas e consultar informações sobre a manifestação voluntária de apoio.');
export const dynamic='force-dynamic';
export default function Participate(){const config=publicConfig();const municipalities=dataset.municipalities.filter(m=>m.id&&!m.review).map(m=>({id:m.id!,name:m.name}));return <InnerLayout className="signature-portal"><section className="signature-stage" aria-labelledby="signature-title"><div className="signature-shell"><div className="signature-intro"><p className="signature-kicker">BAHIA DO SUL <span>·</span> PARTICIPAÇÃO</p><h1 id="signature-title">Uma história construída por quem vive aqui.</h1><p>Registre sua manifestação voluntária de apoio ao projeto Bahia do Sul. Sua participação é simbólica e ajuda a compor o debate público.</p><ul className="signature-promises"><li>Não é plebiscito nem voto oficial</li><li>Seu nome não aparece em uma lista pública</li><li>Você pode solicitar a exclusão da participação</li></ul><Link className="signature-manifest-link" href="/participar/abaixo-assinado">Leia o texto completo do abaixo-assinado <span aria-hidden="true">↗</span></Link></div><section className="signature-card" aria-labelledby="signature-form-title"><p className="signature-card-kicker">MANIFESTAÇÃO VOLUNTÁRIA</p><h2 id="signature-form-title">Assine o abaixo-assinado</h2><p className="signature-form-lead">Preencha seus dados e leia o aviso de privacidade. Se a coleta estiver aberta, enviaremos um link para confirmar sua participação.</p><ParticipationForm enabled={collectionReady()} siteKey={config.turnstileSiteKey} municipalities={municipalities}/><p className="signature-privacy-link"><Link href="/privacidade">Privacidade e responsável pelo tratamento</Link></p></section></div><p className="signature-legal-note">A assinatura registra apoio à proposta. Não cria juridicamente um Estado e não substitui as etapas previstas na Constituição e na legislação.</p></section></InnerLayout>;}
